"""Build data/sample.duckdb: a small synthetic database that can be committed to GitHub.

The public web page uses it, because the real data/jobs.duckdb stays on your computer.
Everything in it is generated by mock_source.generator. Run from the project folder:
    python make_sample_db.py
"""
import sys
from datetime import date, timedelta
from pathlib import Path

from clean.cleaner import clean_raw
from collect.collector import collect_range
from db.schema import connect, create_tables

SAMPLE_PATH = Path(__file__).parent / "data" / "sample.duckdb"
DAYS = 30


def build(path=SAMPLE_PATH, start=date(2026, 10, 1), days=DAYS):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        path.unlink()
    con = connect(path)
    try:
        create_tables(con)
        collect_range(con, start, start + timedelta(days=days - 1))
        clean_raw(con)
        con.execute("CHECKPOINT")
        return con.execute("SELECT COUNT(*) FROM jobs").fetchone()[0]
    finally:
        con.close()


def main(argv=None):
    rows = build()
    print(f"Wrote {SAMPLE_PATH} with {rows} synthetic postings ({SAMPLE_PATH.stat().st_size // 1024} KB).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
